### ISSUE TITLE
Lecturer

### ISSUE THREAD

**Issue by Texnoer** [Texnoer/A_joint_project#1]
А зачем такое нагромождение у класса Lecturer? Разве он автоматом не должен принимать имя и фамилию от родителя?
class Lecturer(Mentor):
    def __init__(self, name, surname):
        super().__init__(name, surname)

**Comment by ReVadim** [comment]
- def __init__(self, name, surname) это для самой программы. Объявление класса.
- super().init(name, surname) это перевод в родитель. (Ссылка)

**Comment by ReVadim** [comment]
https://github.com/Texnoer/A_joint_project/blob/820a7fb23bc0548a9c4569476e5a6476a0740c09/main.py#L42-L43

- Лишние строчки

Чтобы вставить код из файла:

1. Вверху вкладка <code>
2. Открываешь нужный файл и слева до номера строки жмешь мышкой
3. Откроется меню на выбор
4. просто copy / paste или ссылкой (как у меня)
