### ISSUE TITLE
Нужна правка

### ISSUE THREAD

**Issue by ReVadim** [Texnoer/A_joint_project#2]
## Изменение оценок

Для лучшего понимания и поиска возможных ошибок измени оценки
Любые цифры от 1 до 9
Иначе при сравнении не будет видно кто лучше

https://github.com/Texnoer/A_joint_project/blob/820a7fb23bc0548a9c4569476e5a6476a0740c09/main.py#L77-L79

**Comment by Texnoer** [comment]
Это понятно, до этого ещё добраться надо. Там ещё методы сравнения написать сначала нужно.
